<?php
/** @var \ActiveCampaign\SyncLog\Block\Adminhtml\View\Log $block */
$collection = call_user_func_array('array_merge', $block->getLogCollection());
?>
<div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
    <div class="page-actions-inner" data-title="ActiveCampaign Log Information">
        <div class="page-actions-buttons">
            <button id="create_back_button" onclick="window.location.href = '<?php echo $block->getUrl('synclog/index/index') ?>'" title="Back" type="button" class="action-default scalable" data-ui-id="back-button-create-back-button-button">
                <span>< Back</span>
            </button>
        </div>
    </div>
</div>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */ ?>
<section class="admin__page-section log-view-information">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Logs') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item log-information">
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary log-information-table">
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Type: ') ?></th>
                        <td><?php echo $collection['type'] ?></td>
                    </tr>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Method: ') ?></th>
                        <td><?php echo $collection['method'] ?></td>
                    </tr>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Status: ') ?></th>
                        <td><?php echo $collection['status'] ?></td>
                    </tr>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Endpoint: ') ?></th>
                        <td><?php echo $collection['endpoint'] ?></td>
                    </tr>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Request: ') ?></th>
                        <td><?php echo $collection['request'] ?></td>
                    </tr>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Response: ') ?></th>
                        <td><?php echo $collection['response'] ?></td>
                    </tr>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Errors: ') ?></th>
                        <td><?php echo $collection['errors'] ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</section>
