<?php

use ActiveCampaign\Newsletter\Block\Adminhtml\System\Config\NewsletterSyncStatus;

/**
 * @var NewsletterSyncStatus $block
 */
?>

<table cellspacing="0" class="form-list">
    <tbody>
    <tr>
        <td class="label"></td>
        <td class="value">
            <div class="messages">
                <div class="message message-notice">
                    <div>
                        <?= $block->escapeHtml(__("Total Newsletters :")) ?>
                        <strong><?= $block->escapeHtml(__($block->getTotalNewsletter())) ?></strong>
                    </div>
                </div>
            </div>
            <div class="messages">
                <div class="message message-notice">
                    <div>
                        <?= $block->escapeHtml(__("Synced Newsletter :")) ?>
                        <strong><?= $block->escapeHtml(__($block->getSyncNewsletter())) ?></strong>
                    </div>
                </div>
            </div>
            <div class="messages">
                <div class="message message-notice">
                    <div>
                        <?= $block->escapeHtml(__("Not Synced Newsletter :")) ?>
                        <strong><?= $block->escapeHtml(__($block->getNotSyncNewsletter())) ?></strong>
                    </div>
                </div>
            </div>
            <div class="messages">
                <div class="message message-notice">
                    <div>
                        <?= $block->escapeHtml(__("Fail Synced Newsletter :")) ?>
                        <strong><?= $block->escapeHtml(__($block->getFailedSync())) ?></strong>
                    </div>
                </div>
            </div>
        </td>
        <td class></td>
    </tr>
    </tbody>
</table>

