<?php
use ActiveCampaign\Order\Block\Adminhtml\System\Config\OrderSyncStatus;
use Magento\Framework\Escaper;

/**
 * @var OrderSyncStatus $block
 * @var Escaper $escaper
 */
?>
<table cellspacing="0" class="form-list">
    <tbody>
    <tr>
        <td class="label"></td>
        <td class="value">
            <div class="messages">
                <div class="message message-notice" >
                    <div>
                        <?= $escaper->escapeHtml(__("Total Orders :")) ?>
                        <strong><?= $escaper->escapeHtml(__($block->getTotalOrder())) ?></strong>
                    </div>
                </div>
            </div>
            <div class="messages">
                <div class="message message-notice" >
                    <div>
                        <?= $escaper->escapeHtml(__("Synced Orders :")) ?>
                        <strong><?= $escaper->escapeHtml(__($block->getSyncOrder())) ?></strong>
                    </div>
                </div>
            </div>
            <div class="messages">
                <div class="message message-notice" >
                    <div>
                        <?= $escaper->escapeHtml(__("Not Synced Orders :")) ?>
                        <strong><?= $escaper->escapeHtml(__($block->getNotSyncOrder())) ?></strong>
                    </div>
                </div>
            </div>
            <div class="messages">
                <div class="message message-notice" >
                    <div>
                        <?= $escaper->escapeHtml(__("Fail Synced Orders :")) ?>
                        <strong><?= $escaper->escapeHtml(__($block->getFailedSync())) ?></strong>
                    </div>
                </div>
            </div>
        </td>
        <td class></td>
    </tr>
    </tbody>
</table>
