<?php
use ActiveCampaign\Customer\Block\Adminhtml\System\Config\CustomerSyncStatus;

/**
 * @var CustomerSyncStatus $block
 */
?>
<table cellspacing="0" class="form-list">
    <tbody>
            <tr>
                <td class="label"></td>
                <td class="value">
                    <div class="messages">
                        <div class="message message-notice" >
                            <div>
                                <?= $escaper->escapeHtml(__("Total Customer :")) ?>
                                <strong><?= $escaper->escapeHtml(__($block->totalCustomer)) ?></strong>
                            </div>
                        </div>
                    </div>
                    <div class="messages">
                        <div class="message message-notice" >
                            <div>
                                <?= $escaper->escapeHtml(__("Synced Customer :")) ?>
                                <strong><?= $escaper->escapeHtml(__($block->syncedCustomer)) ?></strong>
                            </div>
                        </div>
                    </div>
                    <div class="messages">
                        <div class="message message-notice" >
                            <div>
                                <?= $escaper->escapeHtml(__("Not Synced Customer :")) ?>
                                <strong><?= $escaper->escapeHtml(__($block->notSyncedCustomer)) ?></strong>
                            </div>
                        </div>
                    </div>
                    <div class="messages">
                        <div class="message message-notice" >
                            <div>
                                <?= $escaper->escapeHtml(__("Fail Synced Customer :")) ?>
                                <strong><?= $escaper->escapeHtml(__($block->failSyncedCustomer)) ?></strong>
                            </div>
                        </div>
                    </div>
                </td>
                <td class></td>
            </tr>
    </tbody>
</table>
