<?php
use Magento\Framework\Escaper;

/** @var $block ActiveCampaign\Core\Block\Adminhtml\System\Config\ConnectActiveCampaign
* @var Escaper $escaper */

$connectedStores = $block->getConnectedStores();
?>
<p class="note">
    <span><?= $escaper->escapeHtmlAttr(__('Before clicking on this button Please click on Save Config button. ')) ?>
    </span>
</p>
<button class="scalable" type="button" id="<?= $escaper->escapeHtml($block->getHtmlId()) ?>" data-mage-init='{"Connection":{
    "connection": "<?= $escaper->escapeUrl($block->getConnection()) ?>",
    "url": "<?= $escaper->escapeUrl($block->getAjaxUrl()) ?>",
    "elementId": "<?=  $escaper->escapeHtml($block->getHtmlId()) ?>",
    "successText": "<?=  $escaper->escapeHtml($block->getSuccessText()) ?>",
    "failedText": "<?= $escaper->escapeHtmlAttr(__('Failed! Try again?')) ?>",
    "fieldMapping": "<?= $escaper->escapeHtml($block->getFieldMapping()) ?>"}, "validation": {}}'>
    <span id="<?= $escaper->escapeHtml($block->getHtmlId()) ?>_result"><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
</button>
<p class="note">
    <span><?= $escaper->escapeHtmlAttr(__('After clicking on this button Please go to ')) ?>
        <a href="<?= $escaper->escapeUrl($block->getCacheUrl()) ?>"><?= $escaper->escapeHtmlAttr(__('Cache Management ')) ?>
        </a><?= $escaper->escapeHtmlAttr(__('and refresh cache types.')) ?>
    </span>
</p>
<p class="note"><span>&nbsp;</span></p>
<?php if ($block->isDefaultConfig()): ?>
    <?php foreach ($connectedStores as $key => $store): ?>
<div class="messages">
    <div class="message message-notice">
        <div>
            <?= $escaper->escapeHtml(__($store['name'] . " :")) ?>
            <?php if ($store['status']): ?>
                <strong><?= $escaper->escapeHtml(__("Connected")) ?></strong>
            <?php else: ?>
                <strong class="colorRed"><?= $escaper->escapeHtml(__("Disconnected")) ?></strong>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php endforeach; ?>
<?php endif; ?>
