<?php
/**
 * Copyright © Wagento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/* @var $block \ActiveCampaign\AbandonedCart\Block\System\Config\SyncAbandonedCartData */
?>
<script>
require([
    'jquery',
    'prototype'
], function(jQuery){
    var collectSpan = jQuery('#collect_span_field');
    jQuery('#ac_sync_abandoned_cart_button').click(function () {
        var params = {};
        new Ajax.Request('<?= $block->escapeUrl($block->getAjaxUrl()) ?>', {
            parameters: params,
            asynchronous: true,
            onCreate: function() {
                collectSpan.find('.success-icon').hide();
                collectSpan.find('.error-icon').hide();
                collectSpan.find('.processing-icon').show();
                collectSpan.find('.loading-mask').show();
            },
            onSuccess: function(response) {
                var res = response.responseJSON;
                collectSpan.find('.processing-icon').hide();
                collectSpan.find('.loading-mask').hide();
                var resultText = '';
                if (res.success) {
                    resultText = res.success;
                    collectSpan.find('.success-icon').show();
                } else {
                    resultText = res.error;
                    collectSpan.find('.error-icon').show();
                }
                jQuery('#ajax_message_field_span').text(resultText);
                jQuery('#ac_sync_abandoned_cart_button').prop('disabled', false);
            }
        });
    });
});
</script>
<?= $block->getButtonHtml() ?>
<br><br>
<span class="collect-indicator" id="collect_span_field">
    <img class="processing-icon" hidden
        alt="Processing"
        src="<?= $block->escapeUrl($block->getViewFileUrl('images/process_spinner.gif')) ?>"
    />
    <img class="success-icon" hidden
        alt="Success"
        src="<?= $block->escapeUrl($block->getViewFileUrl('images/rule_component_apply.gif')) ?>"
    />
    <img class="error-icon" hidden
        alt="Error"
        src="<?= $block->escapeUrl($block->getViewFileUrl('images/rule_component_remove.gif')) ?>"
    />
    <span id="ajax_message_field_span"></span>
</span>

<p class="note"><span>&nbsp;</span></p>

<div class="messages">
    <div class="message message-notice" >
        <div>
            <?= $block->escapeHtml(__("Total Abandoned Cart :")) ?>
            <strong><?= $block->escapeHtml(__($block->getTotalAbandonedCart())) ?></strong>
        </div>
    </div>
</div>
<div class="messages">
    <div class="message message-notice" >
        <div>
            <?= $block->escapeHtml(__("Synced Abandoned Cart :")) ?>
            <strong><?= $block->escapeHtml(__($block->getSyncAbandonedCart())) ?></strong>
        </div>
    </div>
</div>
<div class="messages">
    <div class="message message-notice" >
        <div>
            <?= $block->escapeHtml(__("Not Synced Abandoned Cart :")) ?>
            <strong><?= $block->escapeHtml(__($block->getNotSyncAbandonedCart())) ?></strong>
        </div>
    </div>
</div>
<div class="messages">
    <div class="message message-notice" >
        <div>
            <?= $block->escapeHtml(__("Fail Synced Abandoned Cart :")) ?>
            <strong><?= $block->escapeHtml(__($block->getFailedSync())) ?></strong>
        </div>
    </div>
</div>
